# Generated by Django 4.2.23 on 2025-07-24 03:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("face_encoding", models.TextField()),
                (
                    "face_image",
                    models.ImageField(blank=True, null=True, upload_to="face_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "Tamu", "verbose_name_plural": "Data Tamu",},
        ),
        migrations.CreateModel(
            name="VisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_purpose",
                    models.CharField(
                        choices=[
                            ("data_service", "Pelayanan Data"),
                            ("meet_staff", "Menemui Pegawai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visit_description", models.TextField()),
                ("visit_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guest_system.guest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kunjungan",
                "verbose_name_plural": "Data Kunjungan",
            },
        ),
    ]
