# Generated by Django 4.2.23 on 2025-07-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_system", "0002_add_dashboard_features"),
        ("guest_system", "0002_dashboard_features_manual"),
    ]

    operations = []
