# Generated by Django 4.2.23 on 2025-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_system", "0003_merge_20250724_1545"),
    ]

    operations = [
        migrations.AlterModelOptions(name="guest", options={},),
        migrations.AlterModelOptions(name="visitlog", options={},),
        migrations.AddField(
            model_name="visitlog",
            name="checkout_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
