# Generated by Django 4.2.23 on 2025-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_system", "0004_alter_guest_options_alter_visitlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitlog",
            name="checkout_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
