# Generated by Django 4.2.23 on 2025-08-04 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "guest_system",
            "0005_visitlog_check_out_time_alter_guest_face_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("kepala_kantor", "Kepala Kantor"),
                            ("sekretaris", "Sekretaris"),
                            ("subbag_umum", "Subbag Umum & Kepegawaian"),
                            ("pst", "Pelayanan Statistik Terpadu"),
                            ("ipds", "Integrasi Pengolahan dan Diseminasi Statistik"),
                            ("distribusi", "Statistik Distribusi"),
                            ("produksi", "Statistik Produksi"),
                            ("sosial", "Statistik Sosial"),
                            ("neraca", "Neraca Wilayah dan Analisis Statistik"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Format: 628xxxxxxxxxx (untuk WhatsApp)",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "office_room",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("available", "Tersedia"),
                            ("busy", "Sedang Sibuk"),
                            ("meeting", "Sedang Rapat"),
                            ("out", "Sedang Keluar"),
                            ("off", "Tidak Masuk"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(
                        blank=True,
                        help_text="Pesan status tambahan",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=True, help_text="Aktifkan notifikasi WhatsApp"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=20, unique=True)),
                (
                    "release_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-release_date"],},
        ),
        migrations.AddField(
            model_name="visitlog",
            name="whatsapp_sent",
            field=models.BooleanField(
                default=False, help_text="Status pengiriman WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="visitlog",
            name="whatsapp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="face_image",
            field=models.ImageField(null=True, upload_to="face_images/"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_registration", "New Registration"),
                    ("guestbook_reminder", "Guestbook Reminder"),
                    ("guestbook_completed", "Guestbook Completed"),
                    ("guest_checkout", "Guest Checkout"),
                    ("long_visit", "Long Visit Warning"),
                    ("staff_meeting_request", "Staff Meeting Request"),
                    ("whatsapp_sent", "WhatsApp Notification Sent"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visitlog",
            name="visit_purpose",
            field=models.CharField(
                choices=[
                    ("data_service", "Pelayanan Data"),
                    ("meet_staff", "Menemui Pegawai/Kepala Kantor"),
                    ("other_activity", "Mengikuti Kegiatan Lainnya"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChangelogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("new", "New Feature"),
                            ("improvement", "Improvement"),
                            ("fix", "Bug Fix"),
                            ("security", "Security Update"),
                            ("breaking", "Breaking Change"),
                        ],
                        default="improvement",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_highlighted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog_items",
                        to="guest_system.version",
                    ),
                ),
            ],
            options={"ordering": ["item_type", "created_at"],},
        ),
        migrations.AddField(
            model_name="notification",
            name="related_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="guest_system.staff",
            ),
        ),
        migrations.AddField(
            model_name="visitlog",
            name="staff_to_meet",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff yang ingin ditemui",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="guest_system.staff",
            ),
        ),
    ]
